# Generated by Django 4.2 on 2023-05-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Zadej žánr', max_length=30, verbose_name='Žánr')),
            ],
            options={
                'verbose_name': 'žánr',
                'verbose_name_plural': 'žánry',
                'ordering': ['name'],
            },
        ),
    ]
