# Generated by Django 4.2 on 2023-05-10 15:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'blank': 'The field has to be filled'}, help_text='Enter your first name', max_length=50, verbose_name='First name')),
                ('surname', models.CharField(error_messages={'blank': 'The field has to be filled'}, help_text='Enter your surname', max_length=50, verbose_name='Surname')),
                ('email', models.EmailField(error_messages={'blank': 'The field has to be filled', 'invalid': 'Invalid email adress', 'unique': 'This email adress is already in use'}, help_text='Enter your email', max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, help_text='Enter your phone number like this: +420 123 123 123', max_length=16, validators=[django.core.validators.RegexValidator('^[+]\\d{3}( \\d{3}){3}$', 'Nesprávně zadané telefonní číslo')], verbose_name='Phone number')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['surname', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Piercer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Add a piercer', max_length=30, verbose_name='Piercer')),
            ],
            options={
                'verbose_name': 'Piercer',
                'verbose_name_plural': 'Piercers',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
