# Generated by Django 4.2 on 2023-05-11 22:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_reservation_salon_delete_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['name'], 'verbose_name': 'Material', 'verbose_name_plural': 'Materials'},
        ),
        migrations.AlterModelOptions(
            name='placement',
            options={'ordering': ['name'], 'verbose_name': 'Placement', 'verbose_name_plural': 'Placements'},
        ),
        migrations.AlterModelOptions(
            name='thickness',
            options={'ordering': ['thickness'], 'verbose_name': 'Thickness', 'verbose_name_plural': 'Thicknesses'},
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, help_text='Enter your phone number like this: +420 123 123 123', max_length=16, validators=[django.core.validators.RegexValidator('^[+]\\d{3}( \\d{3}){3}$', 'Wrong format')], verbose_name='Phone number'),
        ),
    ]
